### ISSUE TITLE
Failed to set EGL_SWAP_BEHAVIOR on surface

### ISSUE THREAD

**Issue by linuxhsj** [princekin-f/EasyFloat#17]
`E/EGL_emulation: tid 1728: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xc917edc0, error=EGL_BAD_MATCH
`
android 8.0上直接崩溃了、其他版本都是可以的。 @princekin-f

**Comment by linuxhsj** [comment]
`    --------- beginning of crash
2019-09-17 21:17:28.465 657-657/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.systemui, PID: 657
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1001)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:968)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:918)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
        at android.graphics.drawable.AdaptiveIconDrawable.updateMaskBoundsInternal(AdaptiveIconDrawable.java:333)
        at android.graphics.drawable.AdaptiveIconDrawable.updateLayerBounds(AdaptiveIconDrawable.java:295)
        at android.graphics.drawable.AdaptiveIconDrawable.onStateChange(AdaptiveIconDrawable.java:782)
        at android.graphics.drawable.Drawable.setState(Drawable.java:775)
        at android.widget.ImageView.drawableStateChanged(ImageView.java:1305)
        at android.view.View.refreshDrawableState(View.java:20012)
        at android.view.View.dispatchAttachedToWindow(View.java:17409)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4955)
        at android.view.ViewGroup.addView(ViewGroup.java:4746)
        at com.android.systemui.statusbar.phone.NotificationIconAreaController.updateIconsForLayout(NotificationIconAreaController.java:247)
        at com.android.systemui.statusbar.phone.NotificationIconAreaController.updateNotificationIcons(NotificationIconAreaController.java:155)
        at com.android.systemui.statusbar.phone.StatusBar.updateNotificationShade(StatusBar.java:1958)
        at com.android.systemui.statusbar.phone.StatusBar.updateNotifications(StatusBar.java:2138)
        at com.android.systemui.statusbar.phone.StatusBar.addNotificationViews(StatusBar.java:6688)
        at com.android.systemui.statusbar.phone.StatusBar.addEntry(StatusBar.java:1629)
        at com.android.systemui.statusbar.phone.StatusBar.onAsyncInflationFinished(StatusBar.java:1646)
        at com.android.systemui.statusbar.notification.NotificationInflater$AsyncInflationTask.onAsyncInflationFinished(NotificationInflater.java:641)
        at com.android.systemui.statusbar.notification.NotificationInflater.finishIfDone(NotificationInflater.java:460)
        at com.android.systemui.statusbar.notification.NotificationInflater.-wrap0(Unknown Source:0)
        at com.android.systemui.statusbar.notification.NotificationInflater$6.onViewApplied(NotificationInflater.java:343)
        at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:3421)
        at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:3401)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2019-09-17 21:17:28.467 367-378/? W/RescueParty: Failed to determine if device was on USB
    java.io.FileNotFoundException: /sys/class/android_usb/android0/state (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at android.os.FileUtils.readTextFile(FileUtils.java:262)
        at com.android.server.RescueParty.isUsbActive(RescueParty.java:340)
        at com.android.server.RescueParty.isDisabled(RescueParty.java:85)
        at com.android.server.RescueParty.notePersistentAppCrash(RescueParty.java:117)
        at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:342)
        at com.android.server.am.AppErrors.crashApplication(AppErrors.java:321)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:14326)
        at com.android.server.am.ActivityManagerService.handleApplicationCrash(ActivityManagerService.java:14308)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:79)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2992)
        at android.os.Binder.execTransact(Binder.java:674)`

**Comment by linuxhsj** [comment]
@princekin-f

**Comment by princekin-f** [comment]
这确实是的奇怪的问题，关键问题在这一行：
```
java.lang.IllegalArgumentException: width and height must be > 0
```

**并且发现，只在启动前台服务的时候崩溃。最后发现是由：前台通知的图标引起的。**

通知图标使用的是应用默认图标：
```
.setSmallIcon(R.mipmap.ic_launcher)
```

**但是在API 26，也就是Android 8.0的情况下，系统使用的是自适应图标：**
```
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
```
并不是直接设置的图片资源，所以在获取图片信息的时候就直接挂掉了...
