### ISSUE TITLE
延迟初始化bug  FloatingWindowHelper  lateinit property params has not been initialized 

### ISSUE THREAD

**Issue by BigBigDeBoy** [princekin-f/EasyFloat#173]
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property params has not been initialized
        at com.lzf.easyfloat.core.FloatingWindowHelper.getParams(FloatingWindowHelper.kt:33)
        at com.lzf.easyfloat.utils.LifecycleUtils.checkHide(LifecycleUtils.kt:85)
        at com.lzf.easyfloat.utils.LifecycleUtils.access$checkHide(LifecycleUtils.kt:15)
        at com.lzf.easyfloat.utils.LifecycleUtils$setLifecycleCallbacks$1.onActivityStopped(LifecycleUtils.kt:50)
        at android.app.Application.dispatchActivityStopped(Application.java:503)

**Comment by zwc456baby** [comment]
调用 Float.show（）内部有可能是 post 异步执行的。

所以如果调用 show 之后，快速调用 dismiss。可能导致问题

**Comment by Liberations** [comment]
如何解决这个问题呢

**Comment by zwc456baby** [comment]
> 我在外部封装了一层，来避免 post 初始化导致问题。
> 
> 之前的调用代码
> 
> ```kotlin
> showFloat(activity, onEnd, onError)
> ```
> 
> 修改后的：
> 
> ```kotlin
>  activity.findViewById<View>(android.R.id.content)?.post {
>         showFloat(activity, onEnd, onError)
>  }
> ```

你这依旧是 post 的方式。最佳方式应该是：检测调用线程：

Thread.currentThread() == Looper.getMainThread()

if true:
    showFloat
else :
    poset(showFloat())

**Comment by princekin-f** [comment]
> 对于这个post 导致的问题。我已经修复并且请求合并代码。只是作者尚未合并。如果急用，可以上我 fork 的仓库编译最新 aar：
> 
> https://github.com/zwc456baby/EasyFloat

异步的创建需求是需要的，如果直接在`onCreate`创建单页面浮窗，获取`windowToken`会为空；
创建结果改成异步回调了，会在`v2.0.4`修复：
```
fun createWindow(callback: CreateCallback) {
        // 如果在onCreate创建单页面浮窗，会存在获取windowToken为空的情况，需要异步创建
        if (config.showPattern == ShowPattern.CURRENT_ACTIVITY && getToken() == null) {
            getActivity()?.findViewById<View>(android.R.id.content)?.run {
                post { callback.onCreate(createWindowInner()) }
                return
            }
            callback.onCreate(false)
            config.callbacks?.createdResult(false, WARN_ACTIVITY_NULL, null)
            config.floatCallbacks?.builder?.createdResult?.invoke(false, WARN_ACTIVITY_NULL, null)
        } else callback.onCreate(createWindowInner())
    }
```
