### ISSUE TITLE
悬浮窗设置动画为空会报错

### ISSUE THREAD

**Issue by mr-bogey** [princekin-f/EasyFloat#185]
--------- beginning of crash
2021-11-03 10:49:58.585 6180-6180 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: top.bogey.autotouch, PID: 6180
    java.lang.IllegalArgumentException: View=xxx.ui.action.ActionPosOverlay{f4859e6 V.E...... ......ID 0,0-30,30} not attached to window manager
        at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
        at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:380)
        at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:99)
        at com.lzf.easyfloat.core.FloatingWindowHelper.enterAnim(FloatingWindowHelper.kt:348)
        at com.lzf.easyfloat.core.FloatingWindowHelper.access$enterAnim(FloatingWindowHelper.kt:30)
        at com.lzf.easyfloat.core.FloatingWindowHelper$addView$2.onLayout(FloatingWindowHelper.kt:136)
        at com.lzf.easyfloat.widget.ParentFrameLayout.onLayout(ParentFrameLayout.kt:40)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2794)

在创建悬浮窗的时候设置setAnimator(null)，显示就直接crash。

EasyFloat.with(MainActivity.activity)
                .setLayout(this)
                .setShowPattern(ShowPattern.ALL_TIME)
                .setTag(String.valueOf(this.hashCode()))
                .setDragEnable(searching)
                .setAnimator(null)
                .setImmersionStatusBar(true)
                .setGravity(Gravity.START | Gravity.TOP, x - (int) (offset * scale), y - (int) (offset * scale))
                .registerCallbacks(new DotCallback(this))
                .show();

**Comment by princekin-f** [comment]
感谢pr，`v2.0.4`见👍

**Comment by woshiluoyong** [comment]
经测试看到:
如果用setLayout(view)这种,setAnimator(null)直接崩溃
如果用setLayout(R.layout.main)这种,setAnimator(null)不会崩溃,但是横屏显示区域超长会被裁剪,但是拖动哈重绘可能就显示完整了,估计就是高宽在横屏时有计算问题
